apiVersion: gateway.kyma-project.io/v2
kind: APIRule
metadata:
  name: v2ray-final
  namespace: default
spec:
  gateway: kyma-system/kyma-gateway
  host: v2-sap.c-06580ab.kyma.ondemand.com
  rules:
    - accessStrategies:
        - handler: allow
          config: {}
      methods:
        - GET
        - POST
      path: /.*
  service:
    name: v2ray-server
    port: 8080
    
